on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run and comment benchmark details

    steps:
      - uses: JayaKrishnaNamburu/behchmark@master
        with:
          secret-token: "${{ secrets.GITHUB_TOKEN }}"
